config/routes.rb
Rails.application.routes.draw do
  # frozen_string_literal: true
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/tasks/new', to: 'tasks#new', as: :new
  post '/tasks/new', to: 'tasks#create'
  get '/tasks', to: 'tasks#index'
  get '/tasks/:id', to: 'tasks#show', as: :task
  get '/tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch '/tasks/:id', to: 'tasks#update'
  delete '/tasks/:id', to: 'tasks#destroy', as: :delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :details, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params['id'])
  end

  def new
  end

  def create
    task = Task.new(task_params)
    if task.save
      redirect_to :tasks
    else
      render :new
    end
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to :tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit</h1>

<%= form_for @task do |f| %>
  Task title  : <%= f.text_field :title %><br />
  Description : <%= f.text_field :details %><br />
  Done        : <%= f.check_box :completed %><br />
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<ul>
  <% @tasks.each do |task| %>
    <li>
      <%= link_to task_path(task) do %>
      <strong><%= task.title %></strong> [<%= task.completed ? "X" : " " %>]<br>
      <% end %>
      <%= task.details %>
    </li>
  <% end %>
</ul>

<%= link_to new_path do %>
  <strong>Add new task</strong>
<% end %>

app/views/tasks/new.html.erb
<h1>Create Task</h1>

<%= form_for :task do |f| %>
  Task title  : <%= f.text_field "[title]" %><br />
  Description : <%= f.text_field "[details]" %><br />
  Done        : <%= f.check_box "[completed]" %><br />
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1>Task</h1>

<h3>[<%= @task.completed ? "X" : " " %>] <%= @task.title %></h3>
<p><%= @task.details %></p>

<%= link_to edit_path(@task) do %>
  <strong>Edit task</strong>
<% end %>
<br>
<br>
<%= link_to delete_path(@task), method: :delete do %>
  <strong>Delete task</strong>
<% end %>